apiVersion: apps/v1
kind: Deployment
metadata:
  name: wav2vec2-catala
  labels:
    app: wav2vec2-catala
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wav2vec2-catala
  template:
    metadata:
      labels:
        app: wav2vec2-catala
    spec:
      imagePullSecrets:
      - name: github-registry
      containers:
        - name: wav2vec2-catala
          image: ghcr.io/ccoreilly/wav2vec2-catala-onnx:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
