apiVersion: v1
kind: Service
metadata:
  name: wav2vec2-catala
  labels:
    app: wav2vec2-catala
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    name: http
  selector:
    app: wav2vec2-catala